# Generated by Django 5.0.2 on 2024-03-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('unit_description', models.CharField(max_length=100)),
                ('unit_lecturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.units')),
            ],
        ),
    ]
