# Generated by Django 5.0.2 on 2024-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_courses_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevents',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
