# Generated by Django 5.0.2 on 2024-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_units_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
                ('course_lecturer', models.CharField(max_length=100)),
            ],
        ),
    ]
