# Generated by Django 5.0.2 on 2024-03-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('unit_description', models.CharField(blank=True, max_length=100)),
                ('unit_lecturer', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.unit'),
        ),
        migrations.DeleteModel(
            name='units',
        ),
    ]
