# Generated by Django 5.0.2 on 2024-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_unit_alter_timetable_unit_delete_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_lecturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
