# Generated by Django 5.0.2 on 2024-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_course_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.ManyToManyField(to='schedule.unit'),
        ),
    ]
