# Generated by Django 5.0.2 on 2024-03-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_student_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
    ]
